In [18]:
import pandas as pd
df = pd.read_csv("C:\\Users\\user\\my_snippet\\synthetic_dataset.csv")
df.shape

(4362, 5)

In [ ]:
o = df[(df["Rating"]>4) & (df["Stock"] == "In Stock") (df["Category"]=="NaN")]
o.dropna()

     Category   Price    Rating     Stock  Discount
11          A  3772.0  4.890750  In Stock      45.0
80          B  4222.0  4.213203  In Stock      20.0
81          A  1962.0  4.976201  In Stock       6.0
100         A  4752.0  4.589988  In Stock       1.0
115         C  3182.0  4.874852  In Stock      49.0
...       ...     ...       ...       ...       ...
4146        C  9007.0  4.094628  In Stock      15.0
4149        C   136.0  4.919616  In Stock      12.0
4185        C  9911.0  4.492138  In Stock      46.0
4272        B  2443.0  4.444351  In Stock      27.0
4333        D  2424.0  4.716295  In Stock      49.0

[72 rows x 5 columns]

In [41]:
df[df.isna()]

     Category  Price  Rating Stock  Discount
0         NaN    NaN     NaN   NaN       NaN
1         NaN    NaN     NaN   NaN       NaN
2         NaN    NaN     NaN   NaN       NaN
3         NaN    NaN     NaN   NaN       NaN
4         NaN    NaN     NaN   NaN       NaN
...       ...    ...     ...   ...       ...
4357      NaN    NaN     NaN   NaN       NaN
4358      NaN    NaN     NaN   NaN       NaN
4359      NaN    NaN     NaN   NaN       NaN
4360      NaN    NaN     NaN   NaN       NaN
4361      NaN    NaN     NaN   NaN       NaN

[4362 rows x 5 columns]

In [12]:
df.notna().sum()

Category    1614
Price       4188
Rating      2312
Stock       3010
Discount    3970
dtype: int64

In [15]:
df.dropna().head(5)

   Category   Price    Rating         Stock  Discount
6         C   667.0  3.668341      In Stock      41.0
7         A  7125.0  4.983998  Out of Stock       7.0
8         A  2777.0  2.678384      In Stock       6.0
11        A  3772.0  4.890750      In Stock      45.0
15        A  7936.0  3.032832      In Stock      44.0

In [17]:
df[df["Stock"]=="Out of Stock"].shape

(1497, 5)

In [13]:
df.isna()

      Category  Price  Rating  Stock  Discount
0         True  False   False   True     False
1         True  False   False   True     False
2         True  False    True  False     False
3         True  False   False   True     False
4         True  False    True  False     False
...        ...    ...     ...    ...       ...
4357      True  False   False   True     False
4358     False  False    True  False     False
4359      True  False    True  False     False
4360     False  False   False   True     False
4361      True   True   False   True     False

[4362 rows x 5 columns]