In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\user\my_snippet\DataSets\coffee_shop.csv")
df.head()
df['revenue'] = df['unit_price'] * df['transaction_qty']
df['datetime'] = pd.to_datetime(df['transaction_date']+ ' ' +df['transaction_time'], format='%d-%m-%Y %H:%M:%S')
df['hour'] = df['datetime'].dt.hour
df['month'] = df['datetime'].dt.to_period("M")
df.head()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,revenue,datetime,hour,month
0,1,01-01-2023,07:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.0,2023-01-01 07:06:11,7,2023-01
1,2,01-01-2023,07:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.2,2023-01-01 07:08:56,7,2023-01
2,3,01-01-2023,07:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.0,2023-01-01 07:14:04,7,2023-01
3,4,01-01-2023,07:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.0,2023-01-01 07:20:24,7,2023-01
4,5,01-01-2023,07:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.2,2023-01-01 07:22:41,7,2023-01

In [2]:
#Which product categories have the highest repeat transaction frequency
df.groupby('product_category')['transaction_qty'].sum().sort_values(ascending=False).reset_index()

     product_category  transaction_qty
0              Coffee            89250
1                 Tea            69737
2              Bakery            23214
3  Drinking Chocolate            17457
4            Flavours            10511
5        Coffee beans             1828
6           Loose Tea             1210
7             Branded              776
8  Packaged Chocolate              487

In [3]:
#premium product status
high_price = df['unit_price'].quantile(0.90)
g = df.groupby(['product_detail','unit_price'])['revenue'].sum().reset_index()

# g[g['unit_price'] >= high_price].groupby('product_detail')['revenue'].sum()\
#                                 .plot(xlabel='Product Detail',
#                                       ylabel='Revenue',title='Premium Products Revenue Earning',
#                                       kind='bar')

In [8]:
#store-wise demand
g = df.groupby(['store_location','product_category'])['transaction_qty'].sum().reset_index()
g.sort_values(['store_location','transaction_qty'],
              ascending=[True,False])

     store_location    product_category  transaction_qty
2           Astoria              Coffee            29655
8           Astoria                 Tea            24048
0           Astoria              Bakery             7496
4           Astoria  Drinking Chocolate             6351
5           Astoria            Flavours             2206
3           Astoria        Coffee beans              502
6           Astoria           Loose Tea              344
1           Astoria             Branded              279
7           Astoria  Packaged Chocolate              110
11   Hell's Kitchen              Coffee            30220
17   Hell's Kitchen                 Tea            22980
9    Hell's Kitchen              Bakery             7678
13   Hell's Kitchen  Drinking Chocolate             5672
14   Hell's Kitchen            Flavours             3596
12   Hell's Kitchen        Coffee beans              790
15   Hell's Kitchen           Loose Tea              485
16   Hell's Kitchen  Packaged Chocolate              197
10   Hell's Kitchen             Branded              119
20  Lower Manhattan              Coffee            29375
26  Lower Manhattan                 Tea            22709
18  Lower Manhattan              Bakery             8040
22  Lower Manhattan  Drinking Chocolate             5434
23  Lower Manhattan            Flavours             4709
21  Lower Manhattan        Coffee beans              536
24  Lower Manhattan           Loose Tea              381
19  Lower Manhattan             Branded              378
25  Lower Manhattan  Packaged Chocolate              180

In [9]:
g.loc[
    g.groupby('store_location')['transaction_qty'].idxmax()
]

     store_location product_category  transaction_qty
2           Astoria           Coffee            29655
11   Hell's Kitchen           Coffee            30220
20  Lower Manhattan           Coffee            29375

In [12]:
df.groupby('product_category')['transaction_id'] \
  .nunique()\
    .sort_values(ascending=False)

product_category
Coffee                58416
Tea                   45449
Bakery                22796
Drinking Chocolate    11468
Flavours               6790
Coffee beans           1753
Loose Tea              1210
Branded                 747
Packaged Chocolate      487
Name: transaction_id, dtype: int64